version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_dataset_marr:
    run: ehrql:v1 generate-dataset analysis/dm_reg_dataset_martina.py --output output/dataset_dm_marr.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset_dm_marr.csv.gz

  generate_report:
    run: r:latest analysis/dm_age_distrib.R
    needs: [generate_dataset_marr]
    outputs:
      moderately_sensitive:
        chart: output/report_histo_dm_marr.png