version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 1000

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

  generate_hyp_reg_dataset:
      run: >
        ehrql:v1
        generate-dataset analysis/hyp_reg_dataset.py
        --test-data-file analysis/test_hyp_reg_dataset.py
        --output output/hyp/hyp001_viveck.csv.gz
      outputs:
        highly_sensitive:
          cohort: output/hyp/hyp001_viveck.csv.gz

  generate_dm_reg_dataset_viveck:
    run: >
      ehrql:v1
       generate-dataset analysis/dm_reg_dataset_viveck.py
       --output output/dm/dm017_viveck.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/dm/dm017_viveck.csv.gz

  generate_dm_reg_dataset_milan:
    run: >
      ehrql:v1 
        generate-dataset analysis/dm_reg_dataset_milan.py
        --test-data-file analysis/test_dm_reg_dataset_milan.py
        --output output/dm/dm017_milan.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/dm/dm017_milan.csv.gz

  generate_hyp001_measures:
    run: >
      ehrql:v1 generate-measures analysis/hyp_reg_measures.py
      --output output/hyp/hyp001_measures.csv
    outputs:
      moderately_sensitive:
        measure: output/hyp/hyp001_measures.csv

  generate_hyp001_plots:
    run: > 
      r:latest
        analysis/visualise_measures.R
        --output output/hyp/hyp_plot.png
    needs: [generate_hyp001_measures]
    outputs:
      moderately_sensitive:
        hyp_plot: output/hyp/hyp_plot.png
